<a href="https://colab.research.google.com/github/Prxtector/Math/blob/main/content/introductie/les01_labo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Oefeningen introductie

**Mathematical Foundations - IT & Artificial Intelligence**

---

In dit labo maak je kennis met de tools die we doorheen de cursus zullen gebruiken: Python, NumPy, Matplotlib en Pandas. Je verkent ook de MNIST dataset die als rode draad door de cursus loopt.

Werk de oefeningen in volgorde af. De moeilijkheid neemt geleidelijk toe.

## NumPy en Matplotlib

**NumPy** (Numerical Python) is dé library voor numerieke berekeningen in Python. Het biedt krachtige datastructuren zoals arrays en matrices, en functies voor wiskundige operaties. In machine learning wordt NumPy gebruikt om data voor te stellen en te manipuleren. Bijna alle ML-libraries (PyTorch, TensorFlow, scikit-learn) zijn gebouwd op NumPy.

**Matplotlib** is de standaard library voor visualisatie in Python. Hiermee maak je grafieken, plots en afbeeldingen. Visualisatie is essentieel om data te begrijpen en resultaten te communiceren.

### Handige documentatie

- [NumPy documentatie](https://numpy.org/doc/stable/)
- [Matplotlib documentatie](https://matplotlib.org/stable/contents.html)

## AI gebruiken

Je mag AI-tools (zoals ChatGPT of Claude) gebruiken om zaken op te zoeken of uitleg te vragen. **Maar zorg ervoor dat je alles begrijpt!** Kopieer niet blindelings code zonder te snappen wat er gebeurt.

> **Let op:** Bij het examen is het gebruik van AI niet toegestaan. Je moet de concepten en code zelfstandig kunnen toepassen.

In [18]:
# Voer deze cel eerst uit om alle benodigde libraries te importeren

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml

# Laad de MNIST dataset (dit kan even duren bij de eerste keer)
print("MNIST laden...")
mnist = fetch_openml('mnist_784', version=1, as_frame=False)
X, y = mnist.data, mnist.target.astype(int)
print(f"Geladen: {len(X)} afbeeldingen")

MNIST laden...
Geladen: 70000 afbeeldingen


---

## Oefening 1: NumPy Basics


NumPy is de fundamentele library voor numerieke berekeningen in Python. In deze oefening oefen je met het aanmaken van arrays, de basisstructuur van NumPy.

### Opdracht 1a

Maak een vector aan die de gehele getallen van 1 tot en met 10 bevat. Gebruik hiervoor de functie `np.arange()`. Print de vector en controleer dat deze 10 elementen bevat.

In [19]:
# Maak een vector aan met gehele getallen van 1 tot en met 10
vector = np.arange(1, 11)
# Print de vector
print("De vector is:", vector)
# Controleer het aantal elementen
print("Aantal elementen in de vector:", len(vector))

De vector is: [ 1  2  3  4  5  6  7  8  9 10]
Aantal elementen in de vector: 10


### Opdracht 1b

Maak een matrix aan van 3 rijen en 3 kolommen, volledig gevuld met nullen. Gebruik hiervoor de functie `np.zeros()`. Print de matrix en controleer de shape.

In [20]:
# Maak een matrix aan van 3 rijen en 3 kolommen, volledig gevuld met nullen
matrix_zeros = np.zeros((3, 3))

# Print de matrix
print("De matrix is:\n", matrix_zeros)

# Controleer de shape
print("De shape van de matrix is:", matrix_zeros.shape)

De matrix is:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
De shape van de matrix is: (3, 3)


### Opdracht 1c

Maak een identiteitsmatrix aan van 4 bij 4. Een identiteitsmatrix heeft enen op de diagonaal en nullen elders. Gebruik hiervoor de functie `np.eye()`. Print de matrix.

In [21]:
# Maak een identiteitsmatrix aan van 4 bij 4
identity_matrix = np.eye(4)

# Print de matrix
print("De identiteitsmatrix is:\n", identity_matrix)

De identiteitsmatrix is:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Opdracht 1d

Maak een matrix aan van 2 rijen en 5 kolommen, gevuld met willekeurige gehele getallen tussen 0 en 100. Gebruik hiervoor `np.random.randint()`. Print de matrix, de shape, en bereken het gemiddelde van alle waarden met `matrix.mean()`.

In [22]:
# Maak een matrix aan van 2 rijen en 5 kolommen, gevuld met willekeurige gehele getallen tussen 0 en 100
random_matrix = np.random.randint(0, 101, size=(2, 5))

# Print de matrix
print("De willekeurige matrix is:\n", random_matrix)

# Print de shape
print("De shape van de matrix is:", random_matrix.shape)

# Bereken het gemiddelde van alle waarden
print("Het gemiddelde van de matrixwaarden is:", random_matrix.mean())

De willekeurige matrix is:
 [[49 20 73 83 48]
 [74 78 97 94 40]]
De shape van de matrix is: (2, 5)
Het gemiddelde van de matrixwaarden is: 65.6


---

## Oefening 2: MNIST Verkennen


Nu je de basis van NumPy onder de knie hebt, gaan we de MNIST dataset verkennen. Het is belangrijk om je data goed te begrijpen voordat je er een model op traint.

### Opdracht 2a

Bepaal hoeveel voorbeelden er zijn van elk cijfer in de dataset. Gebruik hiervoor `np.unique()` met de parameter `return_counts=True`. Dit geeft je twee arrays terug: de unieke waarden en hun aantallen. Print het resultaat overzichtelijk.

In [23]:
# Bepaal hoeveel voorbeelden er zijn van elk cijfer
unique_digits, counts = np.unique(y, return_counts=True)

# Print het resultaat overzichtelijk
print("Aantal voorbeelden per cijfer:")
for digit, count in zip(unique_digits, counts):
    print(f"Cijfer {digit}: {count} voorbeelden")

Aantal voorbeelden per cijfer:
Cijfer 0: 6903 voorbeelden
Cijfer 1: 7877 voorbeelden
Cijfer 2: 6990 voorbeelden
Cijfer 3: 7141 voorbeelden
Cijfer 4: 6824 voorbeelden
Cijfer 5: 6313 voorbeelden
Cijfer 6: 6876 voorbeelden
Cijfer 7: 7293 voorbeelden
Cijfer 8: 6825 voorbeelden
Cijfer 9: 6958 voorbeelden


### Opdracht 2b

Bereken de gemiddelde pixelwaarde over alle afbeeldingen in de dataset. Gebruik hiervoor `X.mean()`. Bedenk wat dit getal ons vertelt over de data. Is het dichter bij 0 of bij 255? Wat betekent dit?

In [24]:
# Bereken de gemiddelde pixelwaarde over alle afbeeldingen in de dataset
mean_pixel_value = X.mean()

# Print het resultaat
print(f"De gemiddelde pixelwaarde over alle afbeeldingen is: {mean_pixel_value:.2f}")

De gemiddelde pixelwaarde over alle afbeeldingen is: 33.39


### Opdracht 2c

Bepaal de minimum en maximum pixelwaarden in de dataset met `X.min()` en `X.max()`. Controleer of deze overeenkomen met wat je zou verwachten voor grijswaarden afbeeldingen.

In [25]:
# Bepaal de minimum pixelwaarde
min_pixel_value = X.min()

# Bepaal de maximum pixelwaarde
max_pixel_value = X.max()

# Print de resultaten
print(f"De minimum pixelwaarde in de dataset is: {min_pixel_value}")
print(f"De maximum pixelwaarde in de dataset is: {max_pixel_value}")

De minimum pixelwaarde in de dataset is: 0
De maximum pixelwaarde in de dataset is: 255


### Opdracht 2d

De data in X heeft shape (70000, 784). Wat betekent het eerste getal? Wat betekent het tweede getal? Leg dit uit in je eigen woorden in de markdown cel hieronder.

In [26]:
# Print de shape van X om te controleren:
print(f"Shape van X: {X.shape}")
print(f"Datatype van X: {X.dtype}")

Shape van X: (70000, 784)
Datatype van X: int64


*Jouw uitleg hier:*



---

## Oefening 3: Een Cijfer Visualiseren


Elke afbeelding in MNIST is opgeslagen als een vector van 784 waarden. Om de afbeelding te visualiseren, moeten we deze vector eerst omvormen naar een matrix van 28 bij 28.

### Opdracht 3a

Neem de afbeelding op index 100 uit de dataset X. Dit is een vector van 784 elementen. Gebruik de methode `.reshape(28, 28)` om deze om te vormen naar een matrix van 28 bij 28. Print de shape van beide om te verifiëren dat de transformatie correct is.

In [ ]:
# Jouw code voor opdracht 3a:



### Opdracht 3b

Visualiseer de afbeelding met `plt.imshow()`. Gebruik `cmap='gray'` om de afbeelding in grijswaarden te tonen. Voeg een titel toe die het label van de afbeelding toont. Het label vind je in y op dezelfde index.

In [ ]:
# Jouw code voor opdracht 3b:



### Opdracht 3c

Controleer of de visualisatie overeenkomt met het label. Komt de afbeelding overeen met het cijfer dat het label aangeeft? Probeer ook een paar andere indices om te zien of de labels kloppen.

In [ ]:
# Jouw code voor opdracht 3c (kies een paar andere indices):



---

## Oefening 4: Data als Getallen


Deze oefening helpt je om te begrijpen wat een neuraal netwerk "ziet" wanneer het een afbeelding verwerkt. Het netwerk ziet geen visuele afbeelding, maar enkel een reeks getallen.

### Opdracht 4a

Neem opnieuw de afbeelding op index 100 en reshape deze naar 28 bij 28. Print de matrix met pixelwaarden. Om dit leesbaar te houden, print alleen de middelste 10 rijen (rij 9 tot en met 18) en de middelste 10 kolommen (kolom 9 tot en met 18). Gebruik NumPy slicing: `afbeelding[9:19, 9:19]`.

In [ ]:
# Jouw code voor opdracht 5a:



### Opdracht 4b

Bekijk de geprinte waarden. Waar zie je hoge waarden (dicht bij 255)? Waar zie je lage waarden (dicht bij 0)? Hoe correspondeert dit met de lichte en donkere delen van de afbeelding? Schrijf je observaties in de markdown cel hieronder.

*Jouw observaties hier:*



### Opdracht 4c

In MNIST betekent de waarde 0 dat een pixel volledig zwart is, oftewel de achtergrond. De waarde 255 betekent dat een pixel volledig wit is, oftewel het cijfer zelf. Dit lijkt misschien contra-intuïtief als je gewend bent aan papier waar je met zwarte inkt schrijft.

Bereken hoeveel pixels in de afbeelding op index 100 een waarde groter dan 0 hebben. Dit is het aantal pixels dat deel uitmaakt van het cijfer. Bereken ook welk percentage dit is van het totaal aantal pixels (784).

In [ ]:
# Jouw code voor opdracht 5c:



---

## Oefening 5: Gemiddeld Cijfer


In deze uitdagende oefening bereken je de "gemiddelde" versie van een cijfer. Dit geeft inzicht in wat een neuraal netwerk leert: het probeert de gemeenschappelijke kenmerken van alle voorbeelden van een cijfer te vinden.

### Opdracht 5a

Selecteer alle afbeeldingen uit X waarvan het label gelijk is aan 3. Je kan dit doen met boolean indexing: `X[y == 3]`. Dit geeft je een subset van X met alleen de afbeeldingen van het cijfer 3. Hoeveel afbeeldingen zijn er van het cijfer 3?

In [ ]:
# Jouw code voor opdracht 6a:



### Opdracht 5b

Bereken de gemiddelde afbeelding van alle drieën. Gebruik `np.mean()` met `axis=0` om het gemiddelde te nemen over de eerste as, wat overeenkomt met het gemiddelde per pixel. Het resultaat is een vector van 784 waarden. Reshape deze naar 28 bij 28 en visualiseer het resultaat.

In [ ]:
# Jouw code voor opdracht 6b:



### Opdracht 5c

Doe hetzelfde voor het cijfer 8. Bereken de gemiddelde afbeelding en visualiseer deze naast de gemiddelde 3.

In [ ]:
# Jouw code voor opdracht 6c:



---

## Klaar!

Gefeliciteerd, je hebt de labo-oefeningen van les 1 afgerond. Je hebt nu ervaring met NumPy arrays, Matplotlib visualisaties, en de MNIST dataset die we doorheen de cursus zullen gebruiken.

In de volgende les duiken we dieper in de lineaire algebra en leren we hoe vectoren en matrices de basis vormen voor neurale netwerken.

---

**Mathematical Foundations** | Les 1 Labo | IT & Artificial Intelligence